### ISSUE TITLE
What's the meaning of image_pairs and image_pairs_he?

### ISSUE THREAD

**Issue by walkingwindy** [christianabbet/DnR#1]
Hi, I'm curious about the meaning of 'image_pairs' and 'image_pairs_he' in the dataset. What's the difference between them with 'image' and 'image_he'.

**Comment by christianabbet** [comment]
Hi, thank you for your question. To learn the representation embedding (equation 2, $\mathcal{L}_{divide}$) we need the representation of an image $z_i$ and the representation of an image overlapping with the previous one $z_j$. Here, 'image_pairs' is the image that is overlapping with 'image'. While 'image_pairs_he' is the H&E representation of 'image_pairs'. I added a quick file description in the README.md.
