### ISSUE TITLE
Can't run the code

### ISSUE THREAD

**Issue by Dylan21-Ding** [christianabbet/DnR#2]
I have downloaded the samples.npy and thress weight files,the environment was same as yours,but  I met an error   when running the code. "size mismatch for memory: copying a param with shape torch.Size([1320948, 512]) from checkpoint, the shape in current model is torch.Size([200, 512])." Is this caused by the inconsistent number of datasets?
And if I don't use the pretrain,other error appears, "RuntimeError:Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same",it seems that the model does not use cuda.
So, I need your help,thank you.

**Comment by christianabbet** [comment]
It was a mismatch between the size of the memory bank and the size of the provided set of examples. We updated the code. Note that here we provide a small set of 200 samples that would not be enough for full training.
