### ISSUE TITLE
Add discussions tab?

### ISSUE THREAD

**Issue by andreped** [christianabbet/DnR#3]
Hello! Very interesting work. I remember this being presented at MICCAI in 2020 and I have had the printed paper on my desk ever since.

However, I never got the time to play around with these ideas, especially usage of self-supervised learning. Luckily, seems like I will be doing so soon. I will be integrating your ideas into my own framework and designs, and if I have any issues or similar using the code directly, I hope I can ask you questions? One of the issues I immediantly had was which stain normalization method you used and if it was rapid. I have implemented my own GPU-accelerated Macenko method, both in Torch/TF. However, the method seem to have numerical instabilities, as well as not being perfect in some scenarios.

Perhaps a Discussions tab is more optimal for these types of things (see how to add one [here](https://docs.github.com/en/discussions/quickstart))? I would suggest making one for this repo. It is an integrated tab in GitHub, quite new feature really and just what I felt was needed.

**Comment by christianabbet** [comment]
Hi! I am glad to know you enjoyed the paper! I'm also happy to see that people are developing GPU-accelerated normalization approaches for histology. It will greatly help. Also, good luck with that as I know the optimization process can be tricky. Of course, I am always open to discussing ideas / collaborating especially when it fits my Ph.D. research topic so do not hesitate to contact me and we can organize something (christian.abbet@epfl.ch).

I never heard about this GitHub "discussion" feature. I enabled it, so let's see how it goes.

**Comment by andreped** [comment]
@christianabbet heard rumours that optimization can be tricky. I will let you know if I get any issues, or if I have any questions. I have co-developed a package for GPU-accelerated stain normalization called [torchstain](https://github.com/EIDOSlab/torchstain). Its fully open and can be used as you please. Supports torch, tensorflow, and numpy backends. Still some work that remains there, and more to come, but seems to work great on my use cases. 

And yeah, I will let you know if there are any natural collaborations that could be made :] Thanks!

Will post future questions in the Discussion tab.
